# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore dependencies
        run: dotnet restore "PART 1/POE.csproj"

      - name: Build project
        run: dotnet build "PART 1/POE.csproj" --configuration Release

      - name: Run tests
        run: dotnet tests "PART 1/POE.csproj" --configuration Release
